<?php

namespace AppBundle\Repository;

/**
 * CombatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombatRepository extends \Doctrine\ORM\EntityRepository
{
}
