<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Combat
 *
 * @ORM\Table(name="combat")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CombatRepository")
 */
class Combat
{

    /**
     * @return string
     */
    public function __toString()
    {
        // Return the Site object with "[IDEQUIPE]" format, when  __toString is called.
        return $this->equipe1 . " " . $this->equipe2;
    }

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Equipe")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipe1;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Equipe")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipe2;


    /* Autogenerated methods / variables */
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="resultat", type="string", length=255)
     */
    private $resultat;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Combat
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set resultat
     *
     * @param string $resultat
     *
     * @return Combat
     */
    public function setResultat($resultat)
    {
        $this->resultat = $resultat;

        return $this;
    }

    /**
     * Get resultat
     *
     * @return string
     */
    public function getResultat()
    {
        return $this->resultat;
    }

    /**
     * Set equipe1
     *
     * @param \AppBundle\Entity\Equipe $equipe1
     *
     * @return Combat
     */
    public function setEquipe1(\AppBundle\Entity\Equipe $equipe1)
    {
        $this->equipe1 = $equipe1;

        return $this;
    }

    /**
     * Get equipe1
     *
     * @return \AppBundle\Entity\Equipe
     */
    public function getEquipe1()
    {
        return $this->equipe1;
    }

    /**
     * Set equipe2
     *
     * @param \AppBundle\Entity\Equipe $equipe2
     *
     * @return Combat
     */
    public function setEquipe2(\AppBundle\Entity\Equipe $equipe2)
    {
        $this->equipe2 = $equipe2;

        return $this;
    }

    /**
     * Get equipe2
     *
     * @return \AppBundle\Entity\Equipe
     */
    public function getEquipe2()
    {
        return $this->equipe2;
    }
}
